### PR TITLE
Product Order Practice review

### PR DESCRIPTION
**Pull request by Khanhtran9x**

### CODE REVIEW

**Comment by lhsang** [comment]
image
Duplicated in DAO class => should have a genericAbstract class

**Comment by lhsang** [comment]
image
Always show

**Comment by lhsang** [comment]
image
Unused code. Pls check in other classes.

**Comment by lhsang** [comment]
image
Recheck permission for Clerk/Customer

**Comment by lhsang** [comment]
image
Doublecheck 3.2 requirement

**Comment by lhsang** [comment]
image
validation is duplicated

**Comment by lhsang** [comment]
Should have pagination for datatble

**Comment by lhsang** [comment]
Must trigger wait event when the customer clicks on the confirmation/cancellation email. Nice to have: HTML for email content (add HTML element)

**Comment by Khanhtran9x** [comment]
> Must trigger wait event when the customer clicks on the confirmation/cancellation email. Nice to have: HTML for email content (add HTML element)

image
I already have that, it is called from rest controller
Already tested and working fine

**Comment by Khanhtran9x** [comment]
> image Doublecheck 3.2 requirement

Sure I just updated this, issue was with c:if ajax condition

**Comment by Khanhtran9x** [comment]
> image Recheck permission for Clerk/Customer. Redirect after login?

Sure, just fixed and pushed this

**Comment by lhsang** [comment]
> > image Doublecheck 3.2 requirement
> 
> Sure I just updated this, issue was with c:if ajax condition

We have a property "rendered" in a Primefaces element

**Comment by Khanhtran9x** [comment]
> image Duplicated in DAO class => should have a genericAbstract class

Okay, I just updated this, I have implemented a CRUD respository DAO with common methods in generic
image

**Comment by lhsang** [comment]
> > image Duplicated in DAO class => should have a genericAbstract class
> 
> Okay, I just updated this, I have implemented a CRUD respository DAO with common methods in generic image

It's ok. But you have to pass the "class" parameter for each call. So I suggest another way implemented from an AbstractDAO<T, ID> class instead

**Comment by lhsang** [comment]
image
Should be enable when task is available

**Comment by lhsang** [comment]
3.3 Clerk -> login -> List order instead of Create Order
Create order only for Customer

**Comment by lhsang** [comment]
image
Did you finish order detail page?

**Comment by Khanhtran9x** [comment]
> image Did you finish order detail page?

I am facing issue about this, I triggered one method in bean to update product object again based on the id, but in detail view, it can not get that new object, I am finding solution to fix that

**Comment by lhsang** [comment]
image
Should correct your @ManagedBean lib. Besides you don't need to init new Object in @PostConstruct

**Comment by NhyNhyNguyen** [comment]
image
Should be 90 degrees for connector

**Comment by NhyNhyNguyen** [comment]
image
ProductCost already in the bean -> remove from the data

**Comment by NhyNhyNguyen** [comment]
image
Refactor code and remove unuse import

**Comment by NhyNhyNguyen** [comment]
image
remove if it not use any place

**Comment by NhyNhyNguyen** [comment]
image
 should be make that look more good with highline

**Comment by NhyNhyNguyen** [comment]
image
 where is the full name

**Comment by NhyNhyNguyen** [comment]
File document should be download in verify order of clerk, show file name in UI
image
User clerk can create order -> shoud be hide in ui and double check in logi

**Comment by NhyNhyNguyen** [comment]
image

**Comment by NhyNhyNguyen** [comment]
Update UI - product type dropdown should be same length with input text, and should be in create length and error message can be one line
image

**Comment by NhyNhyNguyen** [comment]
image

**Comment by NhyNhyNguyen** [comment]
Can not create order or clerk verify order if WS for cost does not exists or error

**Comment by NhyNhyNguyen** [comment]
image
 remove this button

**Comment by NhyNhyNguyen** [comment]
image
image
image
image
image
- Should follow text in training mock ui ex: Create Order -> Create an Order, List Of Order
image
- Check all text in mock to do same with UI 
image

**Comment by NhyNhyNguyen** [comment]
Functionality:
- Don't have the WS but can finish the create order. Logic can not create order is right. But should not allow user finish that
- Function download not work in verify order. Should the filename and can be download, should add ui download for detail page same with verify order
image
- Show full status WAIT_FOR_CUSTOMER_CONFIRM -> WAIT FOR CUSTOMER CONFIRM
image
- Update mail show the link for email content
image
- Change color different with different status
image
- After create order, verify order, cancel or confirm should save total cost -> maybe because don't have WS. But It should be show error message and can not verify order
image
- Handle error message when confirm cancel order from customer
image
- Handle error for upload document
image
- Default show task or list of order desc of id. So the newest case in the top after create
image
- After click logout. Can not type in username and password. Need to f5

**Comment by Khanhtran9x** [comment]
> image image image image image
> 
> * Should follow text in training mock ui ex: Create Order -> Create an Order, List Of Order
>   image
> * Check all text in mock to do same with UI
>   image

**Comment by Khanhtran9x** [comment]
> Functionality:
> 
> * Don't have the WS but can finish the create order. Logic can not create order is right. But should not allow user finish that
> * Function download not work in verify order. Should the filename and can be download, should add ui download for detail page same with verify order
>   image
> * Show full status WAIT_FOR_CUSTOMER_CONFIRM -> WAIT FOR CUSTOMER CONFIRM
>   image
> * Update mail show the link for email content
>   image
> * Change color different with different status
>   image
> * After create order, verify order, cancel or confirm should save total cost -> maybe because don't have WS. But It should be show error message and can not verify order
>   image
> * Handle error message when confirm cancel order from customer
>   image
> * Handle error for upload document
>   image
> * Default show task or list of order desc of id. So the newest case in the top after create
>   image
> * After click logout. Can not type in username and password. Need to f5

Already fixed, pls check again

**Pull request closed without merging**
